### ISSUE TITLE
A few errors on create?

### ISSUE THREAD

**Issue by dartdog** [codingdesigner/Survival-Kit#3]
see this create, just after installing: some properties missing? Perhaps I should be ignoring the warnings?
I'm a real newbe at this stuff so warning worry me :-)

Fetching: survivalkit-0.2.0.gem (100%)
Successfully installed survivalkit-0.2.0
1 gem installed
Installing ri documentation for survivalkit-0.2.0...
Installing RDoc documentation for survivalkit-0.2.0...
tom@tom-Satellite-A105:~/Documents/Sass_comp_test$ compass create survproj -r survivalkit -u survivalkit --javascript-dir js --css-dir css
directory survproj/ 
directory survproj/css/ 
directory survproj/js/ 
directory survproj/js/kit/ 
directory survproj/js/libs/ 
directory survproj/js/libs/formalize/ 
directory survproj/sass/ 
directory survproj/sass/partials/01-variables/ 
directory survproj/sass/partials/02-extend/ 
directory survproj/sass/partials/03-defaults/ 
directory survproj/sass/partials/03-defaults/markup/ 
directory survproj/sass/partials/03-defaults/markup/forms/ 
directory survproj/sass/partials/04-grids/ 
directory survproj/sass/partials/05-ui-patterns/ 
directory survproj/sass/partials/05-ui-patterns/drupal/ 
directory survproj/sass/partials/06-sprites/ 
directory survproj/sass/partials/07-layout-design/ 
directory survproj/sass/partials/08-styletile/ 
directory survproj/sass/partials/09-responsive/ 
directory survproj/sass/partials/10-media/ 
directory survproj/sass/partials/11-browser-adjustments/ 
directory survproj/survivalkit/ 
directory survproj/survivalkit/formalize/ 
directory survproj/survivalkit/styletile/ 
   create survproj/config.rb 
   create survproj/sass/style.scss 
   create survproj/sass/selectivizr.scss 
   create survproj/sass/ie.scss 
   create survproj/sass/partials/01-variables/_all.scss 
   create survproj/sass/partials/01-variables/_base.scss 
   create survproj/sass/partials/01-variables/_colors.scss 
   create survproj/sass/partials/01-variables/_fonts.scss 
   create survproj/sass/partials/01-variables/_grids-all.scss 
   create survproj/sass/partials/02-extend/_all.scss 
   create survproj/sass/partials/02-extend/_typography.scss 
   create survproj/sass/partials/03-defaults/_all.scss 
   create survproj/sass/partials/03-defaults/_common.scss 
   create survproj/sass/partials/03-defaults/_font-face.scss 
   create survproj/sass/partials/03-defaults/markup/_edits.scss 
WARNING on line 4:
This selector doesn't have any properties and will not be rendered.
WARNING on line 46:
This selector doesn't have any properties and will not be rendered.
WARNING on line 48:
This selector doesn't have any properties and will not be rendered.
   create survproj/sass/partials/03-defaults/markup/_grouping.scss 
   create survproj/sass/partials/03-defaults/markup/_headers.scss 
   create survproj/sass/partials/03-defaults/markup/_images.scss 
WARNING on line 16:
This selector doesn't have any properties and will not be rendered.
WARNING on line 37:
This selector doesn't have any properties and will not be rendered.
WARNING on line 42:
This selector doesn't have any properties and will not be rendered.
WARNING on line 44:
This selector doesn't have any properties and will not be rendered.
WARNING on line 70:
This selector doesn't have any properties and will not be rendered.
WARNING on line 77:
This selector doesn't have any properties and will not be rendered.
WARNING on line 79:
This selector doesn't have any properties and will not be rendered.
WARNING on line 81:
This selector doesn't have any properties and will not be rendered.
WARNING on line 83:
This selector doesn't have any properties and will not be rendered.
WARNING on line 85:
This selector doesn't have any properties and will not be rendered.
   create survproj/sass/partials/03-defaults/markup/_semantics.scss 
WARNING on line 34:
This selector doesn't have any properties and will not be rendered.
WARNING on line 36:
This selector doesn't have any properties and will not be rendered.
WARNING on line 38:
This selector doesn't have any properties and will not be rendered.
WARNING on line 40:
This selector doesn't have any properties and will not be rendered.
WARNING on line 42:
This selector doesn't have any properties and will not be rendered.
WARNING on line 44:
This selector doesn't have any properties and will not be rendered.
WARNING on line 46:
This selector doesn't have any properties and will not be rendered.
WARNING on line 48:
This selector doesn't have any properties and will not be rendered.
   create survproj/sass/partials/03-defaults/markup/_tables.scss 
   create survproj/sass/partials/03-defaults/markup/forms/_form-defaults.scss 
   create survproj/sass/partials/03-defaults/markup/forms/_formalize.scss 
   create survproj/sass/partials/04-grids/_grids-blueprint.scss 
   create survproj/sass/partials/04-grids/_grids-susy.scss 
   create survproj/sass/partials/05-ui-patterns/_common.scss 
   create survproj/sass/partials/05-ui-patterns/drupal/_ui-patterns.scss 
   create survproj/sass/partials/06-sprites/_sprites.scss 
   create survproj/sass/partials/07-layout-design/_layout.scss 
   create survproj/sass/partials/07-layout-design/_design.scss 
WARNING on line 72:
This selector doesn't have any properties and will not be rendered.
   create survproj/sass/partials/08-styletile/_tile-design.scss 
   create survproj/sass/partials/08-styletile/_tile-layout.scss 
   create survproj/sass/partials/09-responsive/_responsive-blueprint.scss 
   create survproj/sass/partials/09-responsive/_responsive-susy.scss 
   create survproj/sass/partials/10-media/_print.scss 
   create survproj/sass/partials/11-browser-adjustments/_ie.scss 
   create survproj/sass/partials/11-browser-adjustments/_modernizr.scss 
   create survproj/sass/partials/11-browser-adjustments/_selectivizr.scss 
   create survproj/index.html 
   create survproj/404.html 
   create survproj/survivalkit/index.html 
   create survproj/survivalkit/elements-common.html 
   create survproj/survivalkit/elements-html5.html 
   create survproj/survivalkit/elements-ui-patterns-drupal.html 
   create survproj/survivalkit/elements-ui-patterns.html 
   create survproj/survivalkit/elements-typography.html 
   create survproj/survivalkit/styletile/styletile.html 
   create survproj/survivalkit/formalize/formalize_jquery_demo.html 
   create survproj/survivalkit/formalize/formalize_jquery_disabled.html 
   create survproj/survivalkit/formalize/formalize_jquery_errors.html 
   create survproj/.htaccess 
   create survproj/crossdomain.xml 
   create survproj/robots.txt 
   create survproj/humans.txt 
   create survproj/apple-touch-icon.png 
   create survproj/favicon.ico 
   create survproj/js/kit/kit-source.jquery.js 
   create survproj/js/script.js 
   create survproj/js/libs/formalize/prototype.formalize.js 
   create survproj/js/libs/formalize/extjs.formalize.js 
   create survproj/js/libs/formalize/dojo.formalize.js 
   create survproj/js/libs/formalize/jquery.formalize.js 
   create survproj/js/libs/formalize/yui.formalize.js 
   create survproj/js/libs/formalize/mootools.formalize.js 
   create survproj/js/libs/dd_belatedpng.js 
   create survproj/js/libs/jquery-1.6.js 
   create survproj/js/libs/respond.min.js 
   create survproj/js/libs/selectivizr.js 
   create survproj/js/libs/jquery-1.6.min.js 
   create survproj/js/libs/modernizr-2.0.min.js 
   create survproj/js/libs/mootools-core-1.3.1-full-compat-yc.js 
   create survproj/js/libs/plugins.js 
   create survproj/css/style.css 
   create survproj/css/ie.css 
   create survproj/css/selectivizr.css 

---

Congratulations! Your compass project has been created.

You may now add and edit sass stylesheets in the sass subdirectory of your project.

Sass files beginning with an underscore are called partials and won't be
compiled to CSS, but they can be imported into other sass stylesheets.

You can configure your project by editing the config.rb configuration file.

You must compile your sass stylesheets into CSS when they change.
This can be done in one of the following ways:
1. To compile on demand:
    compass compile [path/to/project]
2. To monitor your project for changes and automatically recompile:
    compass watch [path/to/project]

More Resources:
- Website: http://compass-style.org/
- Sass: http://sass-lang.com
- Community: http://groups.google.com/group/compass-users/

You've installed The Coding Designer's Survival Kit. Good for you!

To import your new stylesheets add the following lines of HTML (or equivalent) to your webpage:
<head>
  <link href="/css/style.css" media="all" rel="stylesheet" type="text/css" />
  <link href="/css/selectivizr.css" media="all" rel="stylesheet" type="text/css" />
  <link href="/css/ie.css" media="all" rel="stylesheet" type="text/css" />
</head>
tom@tom-Satellite-A105:~/Documents/Sass_comp_test$

**Comment by codingdesigner** [comment]
Those are compilation warnings, but they're intentional. I set up the sass files with many stub selectors that have no css properties. This way you can fill them in with the values you want, or simply leave them blank. If you leave them blank sass omits them at compilation, bit issues a warning on the assumption that you wanted to add a style there. I don't know of a way to suppress that warning during installation.

**Comment by dartdog** [comment]
Thanks for the info,, a note in the docs would have let me avoid asking :-)

**Comment by codingdesigner** [comment]
Thanks for the feedback. I added that note to the readme. I hope it wasn't too frustrating.
