### ISSUE TITLE
When creating a project or using compass watch, I see the following error.

### ISSUE THREAD

**Issue by jeffscottward** [codingdesigner/Survival-Kit#5]
NoMethodError on line 94 of /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb: undefined method `deep_copy' for ["(", "max-width", ": ", $max, ")"]:Array

**Comment by codingdesigner** [comment]
you mentioned on twitter that the problem went away. Closing until it resurfaces.

**Comment by jeffscottward** [comment]
Yea I think it was an outdated compass install
