### ISSUE TITLE
Error on: compass create kit -r survivalkit -u survivalkit --javascripts-dir js --css-dir css

### ISSUE THREAD

**Issue by onglipo** [codingdesigner/Survival-Kit#7]
error kit/sass/style.scss (Line 24 of kit/sass/partials/01-variables/_colors.scss: Function color-schemer is missing argument $base-color.)
error kit/sass/survivalkit/survivalkit.scss (Line 24 of kit/sass/partials/01-variables/_colors.scss: Function color-schemer is missing argument $base-color.)

**Comment by codingdesigner** [comment]
I'll investigate, but I think this issue is fixed in the next release. I haven't set a date for it, but I think it's nearly ready.

**Comment by jeffscottward** [comment]
Please do!! About to go big with a 6-part 'castle', strongly considering using SK! 
If I could even catch you on the phone that would be great too! 
Pretty please

**Comment by codingdesigner** [comment]
Sorry for the delay. I'm working to get 1.0 ready and lost track of this issue. I did just test it tho, and this issue is fixed in the latest beta. (1.0.beta.8) You can get it by running: 

```
sudo gem install survivalkit --pre
```

https://rubygems.org/gems/survivalkit/versions/1.0.beta.8
