### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by RobertinoValue** [codingdesigner/Survival-Kit#9]
Not trying to make demands. But I noticed that the gem I just installed is quite a bit older than this repo. It creates a project folder with jQuery 1.6, modernizr 2.0 while this repo contains 1.8.2 and 2.6.2 respectively. I did not check any further than this.

I realize that I could upgrade everything myself, but just wanting to know if this is still alive.

TIA,
Robert

**EDIT:** 
The Geared Scrolling submodule failed to download. And the repo homepage shows a 404.

**Comment by codingdesigner** [comment]
Hi @RobertinoValue 
I've been folding the work here into other projects lately and plan to officially deprecate this project soon. The main successor to this work is over here: https://github.com/Team-Sass/generator-style-prototype

**Comment by RobertinoValue** [comment]
Hi @canarymason 
OK I'll checkout the other repo then. Thanks for the pointer.
